
let total =
  900 * String.length("hundred")
+ 891 * String.length("and")
+ 190 * String.length("one")
+ 190 * String.length("two")
+ 190 * String.length("three")
+ 190 * String.length("four")
+ 190 * String.length("five")
+ 190 * String.length("six")
+ 190 * String.length("seven")
+ 190 * String.length("eight")
+ 190 * String.length("nine")
+ 10 * String.length("ten")
+ 10 * String.length("eleven")
+ 10 * String.length("twelve")
+ 10 * String.length("thirteen")
+ 10 * String.length("fourteen")
+ 10 * String.length("fifteen")
+ 10 * String.length("sixteen")
+ 10 * String.length("seventeen")
+ 10 * String.length("eighteen")
+ 10 * String.length("nineteen")
+ 100 * String.length("twenty")
+ 100 * String.length("thirty")
+ 100 * String.length("forty")
+ 100 * String.length("fifty")
+ 100 * String.length("sixty")
+ 100 * String.length("seventy")
+ 100 * String.length("eighty")
+ 100 * String.length("ninety")
+ 1 * String.length("onethousand")

printfn "%d" total