//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

module Euler002

    let euler002 () = 
        let fibseq = 
            Seq.unfold (fun (a, b) -> Some(a, (b, a+b))) (0, 1)
        Seq.sum (Seq.filter (fun n -> n % 2= 0) (fibseq |> Seq.takeWhile (fun n -> (n < 4000000))))